# Generated by Django 3.0.8 on 2020-07-31 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200728_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookmark_users',
            new_name='bookmarked_users',
        ),
    ]
